#!/usr/bin/env python

import subprocess
import sys

def system(command):
    return subprocess.check_output(command.split())

def git(args):
    return system(reduce(lambda x, y: x + y, args, "git "))

def parse_logs():
    logs = git("log")
    commits = [x for x
                   in logs.split("\n")
                   if x.startswith("commit ")]
    aaa = [puts(x) for x in logs.split("commit ")]

def puts(x):
    print x
    return x

def get_commit(x):
    return x.strip("commit").strip()[0:9]

if len(sys.argv) < 2:
    sys.exit("\nyou need argument\n") 

option = sys.argv[1]

if option == "log":
    parse_logs()
